version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
  
max_jobs: 1
  
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
image: 
  - Visual Studio 2017
  - Ubuntu

environment:
  matrix:
    - ARCH: arm
    - ARCH: arm64
    - ARCH: amd64
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOCKER_USER:
    secure: aWWvOk1BRRRvZN9wg/Rgag==
  DOCKER_PASS:
    secure: qPnE3V4kK9N1gkeUT1itBQ==
  GITHUB_TOKEN:
    secure: 8TTYoYftaQU6mmYd6iPM9aRsxW7PHfxMsseIY5D2CrjXp02Pt7YOtwNH/LiMVmaq
  APPVEYOR_REPO_TAG_NAME: 1.1.0

matrix:
  exclude:
    - image: Visual Studio 2017
      ARCH: arm
    - image: Visual Studio 2017
      ARCH: arm64
    
install:
  - docker version

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

deploy_script:
  - ps: ./deploy.ps1
  
deploy:
  release: v$(APPVEYOR_REPO_TAG_NAME)
  description: 'Release'
  provider: GitHub
  auth_token:
    secure: 8TTYoYftaQU6mmYd6iPM9aRsxW7PHfxMsseIY5D2CrjXp02Pt7YOtwNH/LiMVmaq
  artifact: /ServerManager-*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    ARCH: amd64
    DEPLOY: "yes"
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu