version: 1.0.{build}
image: Visual Studio 2017
image: Ubuntu

environment:
  matrix:
    - ARCH: arm
    - ARCH: amd64
    
install:
  - docker version

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

deploy_script:
  - ps: ./deploy.ps1